### ISSUE TITLE
Websocket support?

### ISSUE THREAD

**Issue by IMB11** [Auros/Cherry#9]
I have a system that is setup to grab Youtube chat messages and do stuff with them, I was wondering if there would be any way to trigger song requests via a websocket system? Pretty sure old song request manager had them.

**Comment by Auros** [comment]
It doesn't exist in Cherry natively, but one can relatively easily make a mod with an implementation of ICherryRequestSource and bind that to the app container. I made this so people can extend Cherry to their desire without having to make a fork or private version.

**Comment by IMB11** [comment]
Awesome, I'll take a look.

**Comment by Auros** [comment]
Feel free to ping me in BSMG if you need any assistance or guidance
